CREATE DATABASE QUAN_LY_NHA_XE
USE QUAN_LY_NHA_XE
GO

--NHAN VIEN
CREATE TABLE NHAN_VIEN(
MA_NV CHAR(50) NOT NULL,CHECK (MA_NV LIKE 'NVVE[0-9][0-9][0-9]' OR MA_NV LIKE 'QL[0-9][0-9][0-9]' OR MA_NV LIKE 'TAI[0-9][0-9][0-9]'
OR MA_NV LIKE 'ADMIN[0-9][0-9][0-9]'),
TEN_TK CHAR(50),
TEN_NV NVARCHAR,
NGAY_SINH DATE,
GIOI_TINH CHAR(50),
CMND CHAR(50) NOT NULL UNIQUE,
DIA_CHI NVARCHAR(100),
SDT CHAR(50),
CHUC_VU NVARCHAR(50),
PRIMARY KEY(MA_NV),
)
GO
--TAI_KHOAN
CREATE TABLE TAI_KHOAN(
MA_NV CHAR(50) NOT NULL,CHECK (MA_NV LIKE 'NVVE[0-9][0-9][0-9]' OR MA_NV LIKE 'QL[0-9][0-9][0-9]' OR MA_NV LIKE 'TAI[0-9][0-9][0-9]'
OR MA_NV LIKE 'ADMIN[0-9][0-9][0-9]'),
MAT_KHAU CHAR(50),
PRIMARY KEY(MA_NV),
FOREIGN KEY(MA_NV) REFERENCES NHAN_VIEN(MA_NV)
)
GO
--QUAN_LY
CREATE TABLE QUAN_LY(
MA_QL CHAR(50) NOT NULL,CHECK (MA_QL LIKE 'QL[0-9][0-9][0-9]'),
LUONG_CO_BAN CHAR(50),
PHU_CAP CHAR(50),
TIEN_LUONG CHAR(50),
PRIMARY KEY(MA_QL),
FOREIGN KEY(MA_QL) REFERENCES NHAN_VIEN(MA_NV)
)
GO
--NHAN_VIEN_VE
CREATE TABLE NV_VE(
MA_NVVE CHAR(50) NOT NULL,CHECK (MA_NVVE LIKE 'NVVE[0-9][0-9][0-9]'),
LUONG_CO_BAN CHAR(50),
PHU_CAP CHAR(50),
TIEN_LUONG CHAR(50),
PRIMARY KEY(MA_NVVE),
FOREIGN KEY(MA_NVVE) REFERENCES NHAN_VIEN(MA_NV)
)
GO
--TAI_XE
CREATE TABLE TAI_XE(
MA_TAI CHAR(50) NOT NULL,CHECK (MA_TAI LIKE 'TAI[0-9][0-9][0-9]'),
LUONG_CO_BAN CHAR(50),
PHU_CAP CHAR(50),
TIEN_LUONG CHAR(50),
PRIMARY KEY(MA_TAI),
FOREIGN KEY(MA_TAI) REFERENCES NHAN_VIEN(MA_NV)
)
GO
--BANG_LAI
CREATE TABLE BANG_LAI(
MA_BL CHAR(50),
MA_TAI CHAR(50) NOT NULL,CHECK (MA_TAI LIKE 'TAI[0-9][0-9][0-9]'),
LOAI_BANG CHAR(50),
PRIMARY KEY(MA_BL,MA_TAI),
FOREIGN KEY(MA_TAI) REFERENCES TAI_XE(MA_TAI)
)
GO

--LICH_TRINH
CREATE TABLE LICH_TRINH(
MA_CHUYEN CHAR(50)NOT NULL UNIQUE,
MA_QL CHAR(50) NOT NULL,CHECK (MA_QL LIKE 'QL[0-9][0-9][0-9]'),
GIO_KH TIME,
NGAY_KH DATE,
SO_XE CHAR(50),
SO_LUONG_GHE CHAR(50),
GIA_VE CHAR(50),
TEN_CHUYEN NVARCHAR(50),
PRIMARY KEY(MA_CHUYEN,MA_QL),
FOREIGN KEY(MA_QL) REFERENCES QUAN_LY(MA_QL)
)
GO
--THONG_TIN_VE_BAN
CREATE TABLE TT_VE_BAN(
MA_VE CHAR(50) NOT NULL UNIQUE,
MA_NVVE CHAR(50) NOT NULL,CHECK (MA_NVVE LIKE 'NVVE[0-9][0-9][0-9]'),
SDT_HK CHAR(50)NOT NULL UNIQUE,
TEN_HK NVARCHAR(50),
TEN_CHUYEN NVARCHAR(50),
SO_GHE CHAR(50),
SO_XE CHAR(50),
GIO_KH TIME,
NGAY_KH DATE,
GIA_VE CHAR(50),
PRIMARY KEY(MA_VE,MA_NVVE,SDT_HK),
FOREIGN KEY(MA_NVVE) REFERENCES NV_VE(MA_NVVE)
)
GO

--THONG_KE
CREATE TABLE PHIEU_TK(
SO_PHIEU CHAR(50) NOT NULL UNIQUE,
MA_QL CHAR(50) NOT NULL,CHECK (MA_QL LIKE 'QL[0-9][0-9][0-9]'),
NGAY_TK DATE,
DOANH_THU CHAR(50),
THU CHAR(50),
CHI CHAR(50),
PRIMARY KEY(SO_PHIEU,MA_QL),
FOREIGN KEY(MA_QL) REFERENCES QUAN_LY(MA_QL)
)
